---
title: "Quantmod III"
author: "cms"
date: "9/4/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(quantmod)
library(tidyverse)
```


###  Pull down Stock Data for AMZN using Get Symbols

```{r}
tsla<-getSymbols("TSLA", auto.assign = F)
head(tsla)
```


### Store Closing Price (adjusted for stock splits)

```{r}
tsla_cl<-tsla$TSLA.Close
head(tsla_cl)
tsla_cl2<- Ad(tsla)
head(tsla_cl2)
```


### What is Lag


```{r}
head(stats::lag(tsla_cl,1))
```


### remove scientific notation


```{r}
options(scipen = 9999)
```

### Create daily % change vector

```{r}
daily_change<-tsla_cl/stats::lag(tsla_cl,1)-1
head(daily_change)
```

### Look at Histogram of Percentage Change

```{r}
hist(daily_change,40,col = "green")
```




```{r}
buy_signal<-.04
```

### Loop over all trading days (except the first)
```{r}
signal<-c(NULL)
```


```{r}
for(i in 2:length(tsla_cl)) {
  if (daily_change[i]>buy_signal) {
 signal[i]<- 1
  } else
  signal[i]<- 0
} 
head(signal,40)
```


### Reclassify signal to an xts object (tying it to a date)


```{r}

signal<-reclass(signal,tsla_cl)
head(signal,20)
```


### Chart the Series


```{r}
chartSeries(tsla_cl,
            type="1",
            subset = "2022-01-01::2022-01-10",
            theme=chartTheme("white")
            )
quantmod:::get.current.chob
addTA(signal,type='S',col='red')
```


### Add signal line to see how the model performs


```{r}
quantmod:::get.current.chob
```



